// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Analyzes ransomware behavior based on provided logs and generates a comprehensive report.
 *
 * - analyzeRansomwareBehavior - Asynchronously analyzes ransomware behavior and returns a report.
 * - AnalyzeRansomwareBehaviorInput - Defines the input schema for the analysis, including file system logs, registry logs, and network logs.
 * - AnalyzeRansomwareBehaviorOutput - Defines the output schema for the analysis, including a summary of common ransomware behaviors and characteristics.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeRansomwareBehaviorInputSchema = z.object({
  fileSystemLogs: z
    .string()
    .describe('Logs detailing file system changes made by the ransomware.'),
  registryLogs: z.string().describe('Logs detailing registry modifications.'),
  networkLogs: z
    .string()
    .describe('Logs capturing network traffic generated by the ransomware.'),
});

export type AnalyzeRansomwareBehaviorInput = z.infer<
  typeof AnalyzeRansomwareBehaviorInputSchema
>;

const AnalyzeRansomwareBehaviorOutputSchema = z.object({
  summary: z
    .string()
    .describe(
      'A detailed summary of the ransomware behavior, including common patterns and characteristics.'
    ),
});

export type AnalyzeRansomwareBehaviorOutput = z.infer<
  typeof AnalyzeRansomwareBehaviorOutputSchema
>;

export async function analyzeRansomwareBehavior(
  input: AnalyzeRansomwareBehaviorInput
): Promise<AnalyzeRansomwareBehaviorOutput> {
  return analyzeRansomwareBehaviorFlow(input);
}

const analyzeRansomwareBehaviorPrompt = ai.definePrompt({
  name: 'analyzeRansomwareBehaviorPrompt',
  input: {schema: AnalyzeRansomwareBehaviorInputSchema},
  output: {schema: AnalyzeRansomwareBehaviorOutputSchema},
  prompt: `You are an expert cybersecurity analyst specializing in ransomware behavior analysis. Based on the provided file system, registry, and network logs, generate a comprehensive report summarizing the common ransomware behaviors and characteristics.

File System Logs: {{{fileSystemLogs}}}
Registry Logs: {{{registryLogs}}}
Network Logs: {{{networkLogs}}}

Analyze the logs and provide a detailed summary of the ransomware's behavior. Be sure to include common patterns.
`,
});

const analyzeRansomwareBehaviorFlow = ai.defineFlow(
  {
    name: 'analyzeRansomwareBehaviorFlow',
    inputSchema: AnalyzeRansomwareBehaviorInputSchema,
    outputSchema: AnalyzeRansomwareBehaviorOutputSchema,
  },
  async input => {
    const {output} = await analyzeRansomwareBehaviorPrompt(input);
    return output!;
  }
);
